### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by heartforit** [nassor/mongoose-history#1]
Everytime i try to use this plugin i get:

story = new hm.HistoryModel(hm.historyCollectionName(this.collection.name, pre

```
                                         TypeError: Cannot read property 'name' of undefined
```

**Comment by libook** [comment]
I have got this too.
mongoose 4.6.5

```javascirpt
theSchema
    .plugin(timestamp)
    .plugin(mongooseHistory, {
        "customCollectionName": "theHistory"
    });
```

I have sub document in my schema.

**Comment by libook** [comment]
Now I know that this is because of the Sub-document.
