### ISSUE TITLE
Plugin does not work.

### ISSUE THREAD

**Issue by mackbrowne** [nassor/mongoose-history#10]
Tried with a range of versions with the meanJS stack (meanjs.org).

My database requests would never return from express. It seemed like mongoose was causing them to time out.

**Comment by zladuric** [comment]
+1, just tried this with mongoose 3.8.25 and my tests timeout. For what it's worth, I have a bunch of `pre('save')`, `pre('update')` plugins, anyIndex plugin and various custom stuff around my models.

**Comment by zladuric** [comment]
Ok, for me, the problem was mongoose version. If I remove the bundled mongoose from mongoose-history dependencies, plugin works.

**Comment by zladuric** [comment]
@nassor would you considering making a mongoose-history#mongoose3 branch for legacy?
For me, cloning [this]
(https://github.com/nassor/mongoose-history/commit/bdbdb10baf8c1294a56228a7c2cc12fd407be131) works for mongoose 3.8.

**Comment by nassor** [comment]
You just need to use the version below 0.4.0.

**Comment by nassor** [comment]
I create a release tag to 3.8 support: https://github.com/nassor/mongoose-history/releases/tag/v0.3
