### ISSUE TITLE
Minor issue (site): href from npmjs -> github

### ISSUE THREAD

**Issue by vaucouleur** [nassor/mongoose-history#11]
Hi,

A Minor issue. For information, the href npmjs -> github has a typo 

(the link in the column on the right, just above the license).

https://www.npmjs.com/package/mongoose-history

Current:

* https://www.npmjs.com/package/github.com/nassor/mongoose-history

Expected:

* https://github.com/nassor/mongoose-history

**Comment by nassor** [comment]
Fixed! Thanks @vaucouleur
