### ISSUE TITLE
Update & Delete can't store to mongoDB

### ISSUE THREAD

**Issue by sulistiana** [nassor/mongoose-history#15]
I have a problem, when processing update & delete can't store to mongoDB

**Comment by nassor** [comment]
Can you give more details?

**Comment by sulistiana** [comment]
var Schema = mongoose.Schema;
var dataTables = require('mongoose-datatables');
var mongooseHistory = require('mongoose-history');

// create a schema
var restaurantSchema = new Schema({
    restoName: String,
    restoPic: String,
    phone: String,
    address: String,
    categoryID: {type: Schema.Types.ObjectId, ref: 'categoryRestaurant'},
    map: { lat: Number, long: Number },
    sumOfTable: Number,
    ownerID: {type: Schema.Types.ObjectId, ref: 'user'},
});
restaurantSchema.plugin(dataTables);

restaurantSchema.plugin(mongooseHistory);

global.Restaurant = mongoose.model('restaurant', restaurantSchema);

**Comment by nassor** [comment]
The problem happens when you

**Comment by theholla** [comment]
@nassor I have the same problem. The plugin correctly creates an initial mongo schema and document when I call `.create()`, but when I call `findByIdAndUpdate()` it does not register the changes.

**Comment by theholla** [comment]
@nassor ah, I see that `findByIdAndUpdate` makes a call directly to the db and by design does not trigger the pre-save hook. I have updated my code to use `findById` and `save` instead to work with this code.
