### ISSUE TITLE
Keep old Value

### ISSUE THREAD

**Issue by minchomilev** [nassor/mongoose-history#16]
is there a way to keep old value of updated field, and 
is there a way to manipulate fields like virtuals for password salt or etc.

**Comment by nassor** [comment]
You want to avoid update operations ou avoid some fields?

**Comment by minchomilev** [comment]
I would like to encript some of the fields or execute a functions over them before save operation.

**Comment by minchomilev** [comment]
actualy I can make some changes over your module. I ll make a pull request after that If you want to push my changes :)

**Comment by minchomilev** [comment]
I found the solution for my self. I am using virtuals to encript the password for my users. And If I change pre('save') to post('save') the password is saved encripted just like I want. May be it ll be a good point to put an option to choose post or pre to use :) Just an advice from my self :) Anyway great job :+1:
