### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by navarroaxel** [nassor/mongoose-history#19]
Hi! The diffOnly option is not available in the last npm version. Can you update the npm registry with the new version?

Thanks!

**Comment by nassor** [comment]
I'm just adding a extra change / tests on this week before update the npm.
The plan is put the **diffOnly** has default.

**Comment by vaucouleur** [comment]
@nassor 
Hi,  
Will mongoose-history support simultaneously two history collections for the same schema, with one in a 'diff-mode', the other in a 'full-mode' ?

That is, for example when an update is made to a field, the first history collection would get just the updated field ('diff'), and the other history would contain the full object.

**Comment by nassor** [comment]
**Easy way:** We should check if has the possibility to add two different instances of the plugin inside the mongoose plugin manager.

**If this is not possible:** Looks like a great addition to the plugin.

**Comment by vaucouleur** [comment]
@nassor Right. 

Something related, mongoose-history could benefit from having the actually diff algorithm configurable. With a proper default, of course, it could be the existing one. 
.. For complex objects, or for specific situations, the existing  String(d[k]) != String(original[k])  is likely not to be enough, for example for comparison of arrays in case where the order does not matter.

https://github.com/nassor/mongoose-history/commit/9b53cf36a205c4bc4c5120459669c3e97439dc44#diff-062ca6caa5f4d69c0d60829425548d48R35

**Comment by vaucouleur** [comment]
@nassor Validated on small example. It works as expected.

**Comment by nassor** [comment]
Updated!
