### ISSUE TITLE
Discussion: Configurable diff algorithm

### ISSUE THREAD

**Issue by vaucouleur** [nassor/mongoose-history#21]
@nassor 

Mongoose-history could benefit from having the diff algorithm configurable. With a proper default, of course, it could be the existing one.. For complex objects, or for specific situations, the existing  String(d[k]) != String(original[k])  is likely not to be enough, for example for comparison of arrays, in case where the order does not matter. What is your opinion about this ?

Algo part that could be turned into a configurable option:

https://github.com/nassor/mongoose-history/commit/9b53cf36a205c4bc4c5120459669c3e97439dc44#diff-062ca6caa5f4d69c0d60829425548d48R35

**Comment by vaucouleur** [comment]
@nassor I'm working on a PR for this, including tests.

**Comment by nassor** [comment]
Great feature. Thanks!
