### ISSUE TITLE
Version rollback

### ISSUE THREAD

**Issue by nassor** [nassor/mongoose-history#24]
Has some (**huge**) inconsistencies at the version 0.5.0. I unpublished that version and rollback to the version 0.4.2.

**I'm rewriting the tests and part of the implemetation to fix that.**

**Comment by nm-ww** [comment]
May I know when will the 0.5.0 version ready as diff only is something I like to leverage on

**Comment by nassor** [comment]
The problem about the diff only functionality is the messy support to the schema pre/post and even more to the schema.post('init'). It's failing at some Mongoose versions and not in others. Probably we should wait for the some future updates to have a reliable functionality.

Automattic/mongoose#3054
Automattic/mongoose#3968

**Comment by nm-ww** [comment]
Thanks for the quick reply, would you suggest alternative or way that I can implement myself with similar functionality? As seems mongoose won't have this fix soon
