### ISSUE TITLE
Ignoring a specific field

### ISSUE THREAD

**Issue by drannex42** [nassor/mongoose-history#28]
Is it possible to ignore a specific field so that when that field is changed it doesn't create a new document in xxxx_history?

Example: 

```
var modelSchema = new mongoose.Schema({
     totalComments = 34,
     title: "Hello world",
)};

```

Whenever "totalComments" gets changed, how do I make mongoose-history ignore it so it **will not** create a history document?

**Comment by anotheri** [comment]
:+1: 

I'd even prefer to track changes for **only a few fields** from model, and ideally to use separate key in model field definition for it. Something like this: 

```
var User = new mongoose.Schema({
    email: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      index: true,
      trackChanges: true // ← it'll be track changes for this field
    },
    name: {
      type: String,
      required: true,
      trim: true,
      trackChanges: true // ← it'll be track changes for this field
    },
    avatar: {  // ← changes for this field won't be tracked 
      type: String
    }
});
```

And to track all fields' changes we could use `trackAllFileds: true` plugin's option.
