### ISSUE TITLE
Npm repository to latest version

### ISSUE THREAD

**Issue by er-sarjan** [nassor/mongoose-history#30]
Hi,

I found that npm repository version point to 0.4.2 but git repository version points to 0.5.0. Is this because current version is not completed or is current repository 0.5.0 usable for production?

**Comment by nassor** [comment]
No, I rollback this version because had a lot of issues.

Currently I'm refactoring the whole code (https://github.com/nassor/mongoose-history/tree/refactoring) to release a version 0.6.0

**Comment by er-sarjan** [comment]
I would like to contribute for this project as I am looking for same kind of functionality. Let me know if you are looking for contributor.
