### ISSUE TITLE
Can't we make versioning while updating!

### ISSUE THREAD

**Issue by pavan612** [nassor/mongoose-history#31]
@nassor This only works in case of .save its not working in .update

**Comment by nassor** [comment]
the .update operation is "atomic" and is hooked in a different way by Mongoose.
I still trying looking an approach to solving this. (looking for help for that)

https://github.com/nassor/mongoose-history/tree/refactoring

**Comment by lucasscarduelli** [comment]
Is there any forecast to implement functionality in .update?

**Comment by nassor** [comment]
Not yet. We completely depend on mongoose for that, and what mongoose does on the updates as atomic operation without returning the new document back on the hooks.
