### ISSUE TITLE
Compatibility with mongoose@5

### ISSUE THREAD

**Issue by navarroaxel** [nassor/mongoose-history#39]
The `mongoose-history` does not support the new mongoose@5. Throws the following error:
```bash
(node:11461) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
```

This is because `mongoose-history` installs `mongoose@4` besides the `mongoose@5` declared in the app's `package.json`.
I think `mongoose` should be moved to `peerDependencies` in this project to fix this issue.

Versions
mongoose-history@0.4.2
mongoose@5.0.1
node@6.12.3
yarn@1.3.2

**Comment by mnifakram** [comment]
+1

**Comment by nassor** [comment]
PR's are always welcome. 👍

**Comment by navarroaxel** [comment]
Of course @nassor ! I have send the PR #40 a few days ago. I hope you can review that 🙈

**Comment by nassor** [comment]
I pushed to NPM: https://www.npmjs.com/package/mongoose-history
