### ISSUE TITLE
Cannot retrieve _id of updated document

### ISSUE THREAD

**Issue by lvndry** [nassor/mongoose-history#47]
When updating a document I can't know what is the _id of the updated document.

**Comment by nassor** [comment]
can you give me an example?

**Comment by iJassar** [comment]
Same issue here!

When I update a document, it does not add the ID of the document under "d"
example:
`{`
"_id": {
    "$oid": "5e79008e8ce8d721709619b9"
  },
  "t": {
    "$date": "2020-03-23T18:31:42.836Z"
  },
  "o": "u",
  "d": {
    "text": "<p>that is the question</p>"
  }
}`

it should be
When I update a document, it does not add the ID of the document under "d"
example:
`{
  "_id": {
    "$oid": "5e79008e8ce8d721709619b9"
  },
  "t": {
    "$date": "2020-03-23T18:31:42.836Z"
  },
  "o": "u",
  "d": {
"_id": { // ****** ID GOES HERE!! *****
      "$oid": "5e78fdbb445c0a13fc1fa193"
    },
    "text": "<p>that is the question</p>"
  }
}`

This is the put route
`app.put("/:id",(req,res)=>{
    var id = req.params.id;
    var newData = req.body.post;
    Post.findByIdAndUpdate(id, newData, (err,post)=>{
        res.send(post.text);
    })
})`

Thank you!
